## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.4
  - nightly
env:
  - DATADEPS_ALWAYS_ACCEPT=true
matrix:
 allow_failures:
 - julia: nightly
notifications:
  email:
    - recipients:
      - robin.deits@gmail.com
    - on_success: never
    - on_failure: change
branches:
  only:
    - master

after_success:
  # push coverage results to Codecov
- julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'